<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;
use App\Models\User;

// Database Seeder Class
class DatabaseSeeder extends Seeder
{
    public function run()
    {
        DB::table('paymentMethods')->insert([
            [
                'id' => 1,
                'title' => 'Razorpay',
                'image' => 'images/payment/1672813725.png',
                'attributes' => 'rzp_key',
                'status' => 1,
                'subtitle' => 'Card, UPI, Net banking, Wallet (Phone Pe, Amazon Pay, Freecharge)',
                'isVisible' => 1,
            ],
            [
                'id' => 3,
                'title' => 'Paypal',
                'image' => 'images/payment/1672813747.png',
                'attributes' => 'clientkey,0',
                'status' => 1,
                'subtitle' => 'Credit/Debit card with an easier way to pay – online and on your mobile.',
                'isVisible' => 1,
            ],
            [
                'id' => 4,
                'title' => 'Stripe',
                'image' => 'images/payment/1672813758.png',
                'attributes' => 'pk_key,sk_key',
                'status' => 1,
                'subtitle' => 'Accept all major debit and credit cards from customers in every country.',
                'isVisible' => 1,
            ],
            [
                'id' => 5,
                'title' => 'Wallet',
                'image' => 'images/payment/1619505033.png',
                'attributes' => '-',
                'status' => 0,
                'subtitle' => 'If complete payment using wallet.',
                'isVisible' => 1,
            ],
            [
                'id' => 6,
                'title' => 'PayStack',
                'image' => 'images/payment/1672813772.png',
                'attributes' => 'pk_key,sk_key',
                'status' => 1,
                'subtitle' => 'Credit/Debit card with an easier way to pay – online and on your mobile.',
                'isVisible' => 1,
            ],
            [
                'id' => 7,
                'title' => 'FlutterWave',
                'image' => 'images/payment/1672813786.png',
                'attributes' => 'FLWSECK_KEY',
                'status' => 1,
                'subtitle' => 'Card, pay with USSD, pay with bank, pay with barter.',
                'isVisible' => 1,
            ],
            [
                'id' => 8,
                'title' => 'Paytm',
                'image' => 'images/payment/1672813797.png',
                'attributes' => 'MID,MKEY,TEST',
                'status' => 1,
                'subtitle' => 'Credit/Debit card, net banking, Paytm wallet.',
                'isVisible' => 1,
            ],
            [
                'id' => 10,
                'title' => 'SenangPay',
                'image' => 'images/payment/1672813807.png',
                'attributes' => '635160135332883,2909-249,TEST',
                'status' => 1,
                'subtitle' => 'Accept all major debit and credit cards from all related banks.',
                'isVisible' => 1,
            ],
            [
                'id' => 11,
                'title' => 'MercadoPago',
                'image' => 'images/payment/1713327382.png',
                'attributes' => 'key,0',
                'status' => 1,
                'subtitle' => 'Card, pay with USSD, pay with bank, pay with barter.',
                'isVisible' => 1,
            ],
            [
                'id' => 12,
                'title' => 'Payfast',
                'image' => 'images/payment/1713327391.png',
                'attributes' => '46f0cd694581a,10000100,0',
                'status' => 1,
                'subtitle' => 'Card, pay with USSD, pay with bank, pay with barter.',
                'isVisible' => 1,
            ],
            [
                'id' => 13,
                'title' => 'Midtrans',
                'image' => 'images/payment/1713327400.png',
                'attributes' => 'client-key,server-key,0',
                'status' => 1,
                'subtitle' => 'Card, pay with USSD, pay with bank, pay with barter.',
                'isVisible' => 1,
            ],
            [
                'id' => 14,
                'title' => '2checkout',
                'image' => 'images/payment/1713327411.png',
                'attributes' => 'id,key,0',
                'status' => 1,
                'subtitle' => 'Card, pay with USSD, pay with bank, pay with barter.',
                'isVisible' => 1,
            ],
            [
                'id' => 15,
                'title' => 'Khalti Payment',
                'image' => 'images/payment/1713327421.png',
                'attributes' => 'live_secret_key,0',
                'status' => 1,
                'subtitle' => 'Card, pay with USSD, pay with bank, pay with barter.',
                'isVisible' => 1,
            ],
        ]);
        // Seed Users Table
        DB::table('users')->insert([
            [
                'name' => 'Brandon Schatz',
                'email' => 'admin@crewcars.com',
                'password' => Hash::make('password123'),
                'status' => 1,
                'role' => 'admin',
                'profilePicture' => 'https://example.com/images/default_profile.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Test User',
                'email' => 'test@example.com',
                'password' => Hash::make('password123'),
                'status' => 1,
                'role' => 'user',
                'profilePicture' => 'https://example.com/images/default_profile.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);

        Role::create(['name' => 'admin']);
        $user = User::find(1);
        $user->assignRole('admin');
        DB::table('cars')->insert([
            [
                'title' => 'Toyota Corolla',
                'userId' => $user['id'],
                'number' => 'ABC123',
                'img' => 'https://example.com/images/toyota_corolla.jpg',
                'status' => true,
                'rating' => 4.5,
                'seats' => 4,
                'ac' => true,
                'driverName' => 'John Doe',
                'driverMobile' => '1234567890',
                'transmission' => 'Automatic',
                'facility' => 'GPS, Bluetooth, Heated Seats',
                'type' => 'Sedan',
                'brand' => 'Toyota',
                'available' => true,
                'rentPrice' => 50.00,
                'rentPriceDriver' => 70.00,
                'engineHp' => 150,
                'priceType' => 1,
                'fuelType' => 'Gasoline',
                'location' => 'Los Angeles, CA',
                'description' => 'A reliable and fuel-efficient sedan perfect for city drives.',
                'pickAddress' => '123 Main St, Los Angeles, CA',
                'pickLat' => 34.052235,
                'pickLng' => -118.243683,
                'totalMiles' => 25000,
                'postId' => 1,
                'minHrs' => 2,
                'isApproved' => 1,
                'rejectComment' => null,
                'mileage' => 25000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'userId' => $user['id'],
                'title' => 'Honda Civic',
                'number' => 'XYZ789',
                'img' => 'https://example.com/images/honda_civic.jpg',
                'status' => true,
                'rating' => 4.7,
                'seats' => 4,
                'ac' => true,
                'driverName' => 'Jane Smith',
                'driverMobile' => '0987654321',
                'transmission' => 'Manual',
                'facility' => 'GPS, Parking Sensors, Sunroof',
                'type' => 'Sedan',
                'brand' => 'Honda',
                'available' => true,
                'rentPrice' => 55.00,
                'rentPriceDriver' => 75.00,
                'engineHp' => 160,
                'priceType' => 1,
                'fuelType' => 'Diesel',
                'location' => 'New York, NY',
                'description' => 'A sporty sedan with great handling and efficiency.',
                'pickAddress' => '456 Broadway, New York, NY',
                'pickLat' => 40.712776,
                'pickLng' => -74.005974,
                'totalMiles' => 30000,
                'postId' => 2,
                'minHrs' => 3,
                'isApproved' => 1,
                'rejectComment' => null,
                'mileage' => 30000,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);

        // Seed Bookings Table
        DB::table('bookings')->insert([
            [
                'carId' => 1,
                'userId' => 1,
                'cityId' => 101,
                'carPrice' => 50.00,
                'priceType' => 'daily',
                'pickupDate' => '2025-03-01',
                'pickupTime' => '09:00 AM',
                'returnDate' => '2025-03-03',
                'returnTime' => '05:00 PM',
                'couId' => 0,
                'couAmt' => 0.00,
                'wallAmt' => 10.00,
                'totalDayOrHr' => 2,
                'subtotal' => 100.00,
                'taxPer' => 7.5,
                'taxAmt' => 7.50,
                'oTotal' => 117.50,
                'pMethodId' => 1,
                'transactionId' => 'TXN123456789',
                'typeId' => 1,
                'brandId' => 3,
                'bookingType' => 'hourly',
                'bookingStatus' => 'confirmed',
                'isRate' => 1,
                'totalRate' => 4.5,
                'rateText' => 'Great service, very clean car!',
                'exterPhoto' => 'https://example.com/images/exterior.jpg',
                'interPhoto' => 'https://example.com/images/interior.jpg',
                'reviewDate' => '2025-03-04',
                'cancelReason' => null,
                'postId' => 2,
                'commission' => 10.00,
                'pickOtp' => 1234,
                'dropOtp' => 5678,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'carId' => 2,
                'userId' => 2,
                'cityId' => 202,
                'carPrice' => 75.00,
                'priceType' => 'hourly',
                'pickupDate' => '2025-04-10',
                'pickupTime' => '02:00 PM',
                'returnDate' => '2025-04-10',
                'returnTime' => '06:00 PM',
                'couId' => 1,
                'couAmt' => 5.00,
                'wallAmt' => 15.00,
                'totalDayOrHr' => 4,
                'subtotal' => 300.00,
                'taxPer' => 8.0,
                'taxAmt' => 24.00,
                'oTotal' => 319.00,
                'pMethodId' => 1,
                'transactionId' => 'TXN987654321',
                'typeId' => 2,
                'brandId' => 5,
                'bookingType' => 'daily',
                'bookingStatus' => 'pending',
                'isRate' => 0,
                'totalRate' => 0.0,
                'rateText' => null,
                'exterPhoto' => 'https://example.com/images/exterior2.jpg',
                'interPhoto' => 'https://example.com/images/interior2.jpg',
                'reviewDate' => null,
                'cancelReason' => 'Customer requested cancellation',
                'postId' => 3,
                'commission' => 15.00,
                'pickOtp' => 4321,
                'dropOtp' => 8765,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
        DB::table('pages')->insert([
            [
                'id' => 1,
                'title' => 'Privacy Policy',
                'status' => 1,
                'description' => '<p>Privacy Policy</p><p>This privacy policy applies to the CarLink - Car Rental Booking App | Rent a Car | Taxi and Self Drive Car Renting | Complete Solution app (hereby referred to as "Application") for mobile devices that was created by CSCODETECH (hereby referred to as "Service Provider") as a Free service. This service is intended for use "AS IS".</p><p><br></p>...<p>If you have any questions regarding privacy while using the Application, or have questions about the practices, please contact the Service Provider via email at support@cscodetech.com.</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'title' => 'Terms & Conditions',
                'status' => 1,
                'description' => '<p>Terms & Conditions</p><p>These terms and conditions apply to the CarLink - Car Rental Booking App...</p><p>Contact Us</p><p>If you have any questions or suggestions about the Terms and Conditions, please do not hesitate to contact the Service Provider at support@cscodetech.com.</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'title' => 'Contact Us',
                'status' => 1,
                'description' => '<p>We’ll start with some questions and get you to the right place.</p><p>Skype: CSCODETECH</p><p>Facebook: CSCODETECH</p><p>WhatsApp: +91 7276465975</p>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'title' => 'Cancellation Policy',
                'status' => 1,
                'description' => '<div>The cancellation policy for CarLink\'s car rental bookings typically depends on various factors such as the type of booking, duration, and specific terms and conditions agreed upon during the reservation process...</div>',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        DB::table('settings')->insert([
            'webname' => 'CarLink',
            'weblogo' => 'images/website/1712638969.png',
            'timezone' => 'Asia/Kolkata',
            'currency' => '$',
            'oneKey' => '****',
            'oneHash' => '****',
            'scredit' => 15,
            'rcredit' => 10,
            'showDark' => 0,
            'tax' => 5.0,
            'showAddCar' => 1,
            'wlimit' => 50.0,
            'commissionRate' => 10.0,
            'contactNo' => '+917276465975',
            'apiKey' => 'key',
            'smsType' => 'Msg91',
            'authKey' => '*****',
            'otpId' => '*****',
            'accId' => '*****',
            'authToken' => '*****',
            'twilioNumber' => '*****',
            'otpAuth' => 'No',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}